name: Auto Merge Problems into Main

on:
  push:
    branches:
      - problems  # Trigger when changes are pushed to the 'problems' branch

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the 'problems' branch (the source branch)
      - name: Checkout problems branch
        uses: actions/checkout@v3
        with:
          ref: problems

      # Step 2: Set up Git (Configure Git user)
      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Checkout the 'main' branch (target branch)
      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      # Step 4: Merge 'problems' into 'main'
      - name: Merge problems into main
        run: |
          git merge problems --no-ff -m "Auto merge 'problems' into 'main' by GitHub Actions"
          
      # Step 5: Push changes to 'main' branch
      - name: Push to main branch
        run: |
          git push origin main

      # Step 6: Optionally, Run tests or checks (Modify as needed)
      - name: Run tests
        run: |
          # Example command to run tests. Replace with your actual test command.
          pytest  # If you are using Python; adjust as per your language/project.

      # Step 7: Notify success or log info
      - name: Notify success
        run: echo "Successfully merged 'problems' into 'main' and ran tests."
