
name: Auto-merge PRs from problems to main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    if: github.event.pull_request.head.ref == 'problems'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
