name: Auto Merge Debug

on:
  push:
    branches:
      - problems  # Trigger on push to 'problems' branch

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Print "Hello, World!"
        run: echo "Hello, World!"
